const colors = {
    brand110: 'brand-110',
    brand: 'brand',
    brand50: 'brand-50',
    primary110: 'primary-110',
    primary: 'primary',
    primary70: 'primary-70',
    primary50: 'primary-50',
    primary20: 'primary-20',
    premium110: 'premium-110',
    premium: 'premium',
    premium50: 'premium-50',
    premium20: 'premium-20',
    white: 'white',
    grey: 'grey',
    transparent: 'transparent',
    success: 'succes',
    success70: 'success70',
    warning: 'warning',
    warning50: 'warning-50',
    breakingNews: 'breaking-news',
    om: 'om',
    carnet: 'carnet',
    ads: 'ads',
    rabaisChoc: 'rabais-choc',
};
export default Object.freeze(colors);
