name: Build CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Install dependencies
              run: yarn
            - name: Build packages
              run: yarn build
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                workingDir: ./react
                projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}