name: Build CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Install dependencies
              run: yarn
            - name: Build packages
              run: yarn build
            - name: Visual regression tests
              env:
                CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
              run: yarn test:chromatic